import { PlayerStats } from "./PlayerStats";
import { Location } from "./Location";
export declare class Settings {
    static zoomScale: number;
    static _tileSize: number;
    static get tileSize(): number;
    static fps: number;
    static tickMs: number;
    static playsAudio: boolean;
    static playsAreaAudio: boolean;
    static inputDelay: number;
    static rotated: string;
    static region: string;
    static displayXpDrops: boolean;
    static lockPOV: boolean;
    static displayFeedback: boolean;
    static metronome: boolean;
    static inventory_key: string;
    static spellbook_key: string;
    static equipment_key: string;
    static prayer_key: string;
    static combat_key: string;
    static tile_markers: Location[];
    static loadout: string;
    static onTask: boolean;
    static player_stats: PlayerStats;
    static is_keybinding: boolean;
    static southPillar: boolean;
    static westPillar: boolean;
    static northPillar: boolean;
    static displayPlayerLoS: boolean;
    static displayMobLoS: boolean;
    static menuVisible: boolean;
    static minimapScale: number;
    static controlPanelScale: number;
    static maxUiScale: number;
    static _isMobileResult: any;
    static use3dView: boolean;
    static mobileCheck(): any;
    static persistToStorage(): void;
    static readFromStorage(): void;
}
