
export enum ItemNames {
  JUSTICIAR_FACEGUARD = 'Justiciar Faceguard',
  JUSTICIAR_CHESTGUARD = 'Justiciar Chestguard',
  JUSTICIAR_LEGGUARDS = 'Justiciar Legguards',
  ARMADYL_CHAINSKIRT = 'Armadyl Chainskirt',
  ARMADYL_CHESTPLATE = 'Armadyl Chestplate',
  AVAS_ASSEMBLER = 'Avas Assembler',
  BARROWS_GLOVES = 'Barrows Gloves',
  CRYSTAL_SHIELD = 'Crystal Shield',
  DEVOUT_BOOTS = 'Devout Boots',
  HOLY_BLESSING = 'Holy Blessing',
  NECKLACE_OF_ANGUISH = 'Necklace of Anguish',
  PEGASIAN_BOOTS = 'Pegasian Boots',
  RING_OF_SUFFERING_I = 'Ring of Suffering (i)',
  TOXIC_BLOWPIPE = 'Toxic Blowpipe',
  TWISTED_BOW = 'Twisted Bow',
  SCYTHE_OF_VITUR = 'Scythe of Vitur',
  KODAI_WAND = 'Kodai Wand',
  ANCESTRAL_ROBETOP = 'Ancestral Robe top',
  ANCESTRAL_ROBEBOTTOM = 'Ancestral Robe bottom',
  RING_OF_ENDURANCE = 'Ring of Endurance',
  STAMINA_POTION = 'Stamina Potion',
}
